### ISSUE TITLE
https://hiveonboard.com/create-account down ?

### ISSUE THREAD

**Issue by daslicht** [christianfuerst/hiveonboard#43]
https://hiveonboard.com/create-account is down ?

**Comment by christianfuerst** [comment]
Everything is working as intended.

Since every account created has a cost of 3 HIVE or an account creation ticket involved - hiveonboard relies on 3rd parties to supply account creation tickets. Right now, nobody is providing those tickets - until this situation changes, no account creation is possible.

I've suggested HIVE witnesses to vote for account creation fee of `0.001 HIVE`- right now most witnesses are voting for `3.000 HIVE` which makes it impossible to fund this project even further.

If major top witnesses agree upon that, the issue will be solved.

**Comment by daslicht** [comment]
I get this in any browser:
![](https://i.imgur.com/DRZGqlU.png)
